export const optionMapping: Record<string, string> = {
    "Biohazard_bag": "BIOHAZ BAG",
    "Gel_Tube": "GEL TUBE",
    "EDTA_Tube": "EDTA TUBE",
    "Gluc_Tube": "GLUC TUBE",
    "Coag_Tube": "COAG TUBE",
    "urine_container": "URINE CONT",
    "Paeds_Gel": "PAEDS GEL",
    "Paeds_FBC": "PAEDS FBC",
    "Paeds_EDTA": "PAEDS EDTA",
    "Stool_Container": "STOOL CONT",
    "Swab_Amies_gel": "SWAB - AMIES (GEL)",
    "Swab_Carry_Blair": "SWAB - CARRY BLAIR",
    "ESR_Tube": "ESR TUBE",
    "24h_urine_container_(BOX)": "24 HRS URINE CONTAINER (BOX)",
    "C&S_Aerobic": "C&S AEROBIC",
    "C&S_Anaerobic": "C&S ANAEROBIC",
    "C&S_Peads": "C&S PAEDS",
    "C&S_Fungal": "C&S FUNGAL",
    "Lithium_Heparin_Tube": "LITHIUM HEP TUBE",
    "G6PD_Paper": "G6PD PAPER",
    "Blood_Spot_Paper": "BLOOD SPOT PAPER",
    "Foam_Box": "FOAM BOX",
    "Parafilm": "PARAFILM",
    "Bijoue_bottle": "BIJOUE BOTTLE",
    "Glass_slides": "GLASS SLIDES",
    "Microscope_Slide": "MICROSCOPE SLIDE",
    "Plain_tube_with_red_stopper": "PLAIN TUBE + RED STOPER",
    "Sodium_Heparin_tube": "SODIUM HEP TUBE"
};